### PR TITLE
Module name changed to sigs.k8s.io/ibm-powervs-block-csi-driver

### PR DESCRIPTION
**Pull request by Madhan-SWE**
- Module name changed to sigs.k8s.io/ibm-powervs-block-csi-driver
- Internal names changed from powervs-csi-driver to ibm-powervs-block-csi-driver

**Other fix in Makefile** :

- The Version for the image was hardcoded as `latest` earlier. Now changed as per variable `VERSION`

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
/lgtm
/approve

**Comment by mkumatag** [comment]
@Madhan-SWE please change the repo name in the github as well.

**Comment by Madhan-SWE** [comment]
@mkumatag repo name changed

**Comment by mkumatag** [comment]
@Rajalakshmi-Girish can you check why PR is not merging even after having lgtm and approval tags

**Comment by Rajalakshmi-Girish** [comment]
> @Rajalakshmi-Girish can you check why PR is not merging even after having lgtm and approval tags

I see below error in tide log:
```
{"base-sha":"0dc89b554512c7f549c108198c426ff65995472e","branch":"main","component":"tide","controller":"sync","error":"status code 404 not one of [200 405 409], body: {\"message\":\"Not Found\",\"documentation_url\":\https://docs.github.com/rest/reference/pulls#merge-a-pull-request\}","file":"prow/tide/tide.go:1247","func":"k8s.io/test-infra/prow/tide.(*Controller).mergePRs","level":"debug","merge-targets":[72],"msg":"Merge failed.","org":"ppc64le-cloud","pr":72,"repo":"ibm-powervs-block-csi-driver","severity":"debug","sha":"666be324fcd0816dd05983c2210e7527811dfd68","time":"2022-01-04T09:29:58Z"}
```
404 might be due to change of org name from `powervs-csi-driver` to `ibm-powervs-block-csi-driver
` while the PR review is in progress..
@mkumatag Can we try re-creating a new PR and check?

**Comment by mkumatag** [comment]
@Madhan-SWE can you please resolve the conflicts?

**Comment by Madhan-SWE** [comment]
Resolving conflicts from UI creates merge commits and that leads to do-not-merge label addition.
Created a new PR with proper rebase: https://github.com/ppc64le-cloud/ibm-powervs-block-csi-driver/pull/75

**Comment by mkumatag** [comment]
merged via #75 , hence can be closed
/close

**Pull request closed without merging**
